// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace LivriaBackend.Tests.BDD.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TS10AnadirUnLibroAlInventarioFeature : object, Xunit.IClassFixture<TS10AnadirUnLibroAlInventarioFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TS10_AnadirLibroInventario.feature"
#line hidden
        
        public TS10AnadirUnLibroAlInventarioFeature(TS10AnadirUnLibroAlInventarioFeature.FixtureData fixtureData, LivriaBackend_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "BDD/Features", "TS10 – Añadir un libro al inventario", "  Como developer\r\n  Quiero agregar un libro nuevo al inventario de Livria\r\n  Para" +
                    " ampliar el catálogo y aumentar las ventas", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 11
  #line hidden
#line 12
    testRunner.Given("TS10 el desarrollador está en la sección de gestión de inventario", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TS10_AC1 – Formulario presenta todos los campos requeridos")]
        [Xunit.TraitAttribute("FeatureTitle", "TS10 – Añadir un libro al inventario")]
        [Xunit.TraitAttribute("Description", "TS10_AC1 – Formulario presenta todos los campos requeridos")]
        public void TS10_AC1FormularioPresentaTodosLosCamposRequeridos()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS10_AC1 – Formulario presenta todos los campos requeridos", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
  this.FeatureBackground();
#line hidden
#line 15
    testRunner.When("TS10 el sistema recibe la solicitud de registro de un nuevo libro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 16
    testRunner.Then("TS10 el sistema debe requerir título del libro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 17
    testRunner.And("TS10 el sistema debe requerir autor del libro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
    testRunner.And("TS10 el sistema debe requerir descripción del libro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 19
    testRunner.And("TS10 el sistema debe requerir stock inicial del libro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 20
    testRunner.And("TS10 el sistema debe requerir género del libro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
    testRunner.And("TS10 el sistema debe requerir idioma del libro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 22
    testRunner.And("TS10 el sistema debe requerir portada del libro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TS10_AC2a – Registro exitoso de un nuevo libro")]
        [Xunit.TraitAttribute("FeatureTitle", "TS10 – Añadir un libro al inventario")]
        [Xunit.TraitAttribute("Description", "TS10_AC2a – Registro exitoso de un nuevo libro")]
        public void TS10_AC2ARegistroExitosoDeUnNuevoLibro()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS10_AC2a – Registro exitoso de un nuevo libro", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
  this.FeatureBackground();
#line hidden
#line 25
    testRunner.Given("TS10 el desarrollador proporciona un libro con título \"Clean Code\" autor \"Robert " +
                        "C. Martin\" género \"non_fiction\" idioma \"english\" y stock 10", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 26
    testRunner.When("TS10 el sistema procesa el alta del nuevo libro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 27
    testRunner.Then("TS10 el libro debe ser creado con estado activo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 28
    testRunner.And("TS10 el libro debe tener precio de venta igual al 165% del precio de compra", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 29
    testRunner.And("TS10 el libro debe aparecer en el listado del inventario", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TS10_AC2b – Registro rechazado por género inválido")]
        [Xunit.TraitAttribute("FeatureTitle", "TS10 – Añadir un libro al inventario")]
        [Xunit.TraitAttribute("Description", "TS10_AC2b – Registro rechazado por género inválido")]
        public void TS10_AC2BRegistroRechazadoPorGeneroInvalido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS10_AC2b – Registro rechazado por género inválido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
  this.FeatureBackground();
#line hidden
#line 32
    testRunner.Given("TS10 el desarrollador proporciona un libro con título \"Drama Book\" autor \"Autor T" +
                        "est\" género \"drama\" idioma \"english\" y stock 5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 33
    testRunner.When("TS10 el sistema procesa el alta del nuevo libro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
    testRunner.Then("TS10 el sistema debe rechazar el libro con un error de género inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TS10_AC2c – Registro rechazado por idioma inválido")]
        [Xunit.TraitAttribute("FeatureTitle", "TS10 – Añadir un libro al inventario")]
        [Xunit.TraitAttribute("Description", "TS10_AC2c – Registro rechazado por idioma inválido")]
        public void TS10_AC2CRegistroRechazadoPorIdiomaInvalido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS10_AC2c – Registro rechazado por idioma inválido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
  this.FeatureBackground();
#line hidden
#line 37
    testRunner.Given("TS10 el desarrollador proporciona un libro con título \"French Book\" autor \"Autor " +
                        "Test\" género \"fiction\" idioma \"french\" y stock 5", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 38
    testRunner.When("TS10 el sistema procesa el alta del nuevo libro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 39
    testRunner.Then("TS10 el sistema debe rechazar el libro con un error de idioma inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="TS10_AC2d – Registro rechazado por stock negativo")]
        [Xunit.TraitAttribute("FeatureTitle", "TS10 – Añadir un libro al inventario")]
        [Xunit.TraitAttribute("Description", "TS10_AC2d – Registro rechazado por stock negativo")]
        public void TS10_AC2DRegistroRechazadoPorStockNegativo()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("TS10_AC2d – Registro rechazado por stock negativo", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
  this.FeatureBackground();
#line hidden
#line 42
    testRunner.Given("TS10 el desarrollador proporciona un libro con título \"Stock Test\" autor \"Autor T" +
                        "est\" género \"fiction\" idioma \"english\" y stock -1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 43
    testRunner.When("TS10 el sistema procesa el alta del nuevo libro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 44
    testRunner.Then("TS10 el sistema debe rechazar el libro con un error de stock inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TS10AnadirUnLibroAlInventarioFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TS10AnadirUnLibroAlInventarioFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
