// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace LivriaBackend.Tests.BDD.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class US18ComprarLibrosDigitalesYFisicosFeature : object, Xunit.IClassFixture<US18ComprarLibrosDigitalesYFisicosFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "US18_ComprarLibros.feature"
#line hidden
        
        public US18ComprarLibrosDigitalesYFisicosFeature(US18ComprarLibrosDigitalesYFisicosFeature.FixtureData fixtureData, LivriaBackend_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "BDD/Features", "US18 – Comprar libros digitales y físicos", "  Como lector\r\n  Quiero poder comprar libros desde la plataforma\r\n  Para acceder " +
                    "a lecturas nuevas de manera inmediata\r\n  O recibir ediciones impresas en mi domi" +
                    "cilio", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 11
  #line hidden
#line 12
    testRunner.Given("existe un cliente con ID 1 y email \"lector@livria.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "BookId",
                        "Title",
                        "Author",
                        "Price",
                        "Quantity"});
            table1.AddRow(new string[] {
                        "1",
                        "El Principito",
                        "Saint-Exupéry",
                        "29.99",
                        "2"});
            table1.AddRow(new string[] {
                        "2",
                        "Cien Años Soledad",
                        "García Márquez",
                        "39.99",
                        "1"});
#line 13
    testRunner.And("el carrito contiene los siguientes ítems:", ((string)(null)), table1, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="US18_AC2a – Compra exitosa sin delivery")]
        [Xunit.TraitAttribute("FeatureTitle", "US18 – Comprar libros digitales y físicos")]
        [Xunit.TraitAttribute("Description", "US18_AC2a – Compra exitosa sin delivery")]
        public void US18_AC2ACompraExitosaSinDelivery()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("US18_AC2a – Compra exitosa sin delivery", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
  this.FeatureBackground();
#line hidden
#line 19
    testRunner.Given("el lector ha revisado su carrito y decide completar la compra", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 20
    testRunner.When("el lector selecciona \"Completar compra\" sin envío a domicilio", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 21
    testRunner.Then("el sistema debe registrar la orden con los ítems del carrito", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 22
    testRunner.And("el total de la orden debe ser 99.97", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
    testRunner.And("el estado inicial de la orden debe ser \"pending\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 24
    testRunner.And("el sistema debe generar un código único de 6 caracteres para la orden", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="US18_AC2b – Compra exitosa con delivery a zona 1")]
        [Xunit.TraitAttribute("FeatureTitle", "US18 – Comprar libros digitales y físicos")]
        [Xunit.TraitAttribute("Description", "US18_AC2b – Compra exitosa con delivery a zona 1")]
        public void US18_AC2BCompraExitosaConDeliveryAZona1()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("US18_AC2b – Compra exitosa con delivery a zona 1", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
  this.FeatureBackground();
#line hidden
#line 27
    testRunner.Given("el lector ha revisado su carrito y decide completar la compra", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 28
    testRunner.When("el lector selecciona \"Completar compra\" con envío a \"Miraflores\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 29
    testRunner.Then("el sistema debe registrar la orden con los ítems del carrito", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 30
    testRunner.And("el total de la orden debe incluir el costo de envío de 5.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 31
    testRunner.And("el total final debe ser 104.97", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
    testRunner.And("el estado inicial de la orden debe ser \"pending\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="US18_AC2c – Compra rechazada sin ítems en el carrito")]
        [Xunit.TraitAttribute("FeatureTitle", "US18 – Comprar libros digitales y físicos")]
        [Xunit.TraitAttribute("Description", "US18_AC2c – Compra rechazada sin ítems en el carrito")]
        public void US18_AC2CCompraRechazadaSinItemsEnElCarrito()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("US18_AC2c – Compra rechazada sin ítems en el carrito", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
  this.FeatureBackground();
#line hidden
#line 35
    testRunner.Given("el carrito del lector está vacío", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 36
    testRunner.When("el lector intenta seleccionar \"Completar compra\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 37
    testRunner.Then("el sistema debe rechazar la compra con un error de carrito vacío", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="US18_AC2d – Compra rechazada por delivery sin shipping details")]
        [Xunit.TraitAttribute("FeatureTitle", "US18 – Comprar libros digitales y físicos")]
        [Xunit.TraitAttribute("Description", "US18_AC2d – Compra rechazada por delivery sin shipping details")]
        public void US18_AC2DCompraRechazadaPorDeliverySinShippingDetails()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("US18_AC2d – Compra rechazada por delivery sin shipping details", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
  this.FeatureBackground();
#line hidden
#line 40
    testRunner.Given("el lector ha revisado su carrito y decide completar la compra", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 41
    testRunner.When("el lector selecciona \"Completar compra\" con delivery pero sin datos de envío", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 42
    testRunner.Then("el sistema debe rechazar la compra con un error de datos de envío", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                US18ComprarLibrosDigitalesYFisicosFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                US18ComprarLibrosDigitalesYFisicosFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
