// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace LivriaBackend.Tests.BDD.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class US19BuscarLibrosYContenidoEnLaAplicacionFeature : object, Xunit.IClassFixture<US19BuscarLibrosYContenidoEnLaAplicacionFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "US19_BuscarLibros.feature"
#line hidden
        
        public US19BuscarLibrosYContenidoEnLaAplicacionFeature(US19BuscarLibrosYContenidoEnLaAplicacionFeature.FixtureData fixtureData, LivriaBackend_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "BDD/Features", "US19 – Buscar libros y contenido en la aplicación", "  Como lector\r\n  Quiero utilizar una barra de búsqueda para encontrar libros y au" +
                    "tores\r\n  Para acceder fácilmente a contenido de interés sin navegar por toda la " +
                    "plataforma", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 10
  #line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "Author",
                        "Genre",
                        "Language"});
            table2.AddRow(new string[] {
                        "El Principito",
                        "Antoine de Saint-Exupéry",
                        "fiction",
                        "español"});
            table2.AddRow(new string[] {
                        "Cien Años de Soledad",
                        "Gabriel García Márquez",
                        "literature",
                        "español"});
            table2.AddRow(new string[] {
                        "El Amor en los Tiempos del Cólera",
                        "Gabriel García Márquez",
                        "literature",
                        "español"});
            table2.AddRow(new string[] {
                        "Don Quijote de la Mancha",
                        "Miguel de Cervantes",
                        "literature",
                        "español"});
#line 11
    testRunner.Given("el catálogo del sistema contiene los siguientes libros:", ((string)(null)), table2, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="US19_AC1a – Búsqueda por título exacto")]
        [Xunit.TraitAttribute("FeatureTitle", "US19 – Buscar libros y contenido en la aplicación")]
        [Xunit.TraitAttribute("Description", "US19_AC1a – Búsqueda por título exacto")]
        public void US19_AC1ABusquedaPorTituloExacto()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("US19_AC1a – Búsqueda por título exacto", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
  this.FeatureBackground();
#line hidden
#line 19
    testRunner.Given("el lector inicia una consulta de búsqueda", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 20
    testRunner.When("el sistema recibe el término \"El Principito\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 21
    testRunner.Then("el sistema debe retornar 1 resultado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 22
    testRunner.And("el resultado debe contener el libro \"El Principito\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
    testRunner.And("cada resultado debe tener título, autor e imagen no vacíos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="US19_AC1b – Búsqueda por título parcial")]
        [Xunit.TraitAttribute("FeatureTitle", "US19 – Buscar libros y contenido en la aplicación")]
        [Xunit.TraitAttribute("Description", "US19_AC1b – Búsqueda por título parcial")]
        public void US19_AC1BBusquedaPorTituloParcial()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("US19_AC1b – Búsqueda por título parcial", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
  this.FeatureBackground();
#line hidden
#line 26
    testRunner.Given("el lector inicia una consulta de búsqueda", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 27
    testRunner.When("el sistema recibe el término \"Años\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 28
    testRunner.Then("el sistema debe retornar al menos 1 resultado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 29
    testRunner.And("cada resultado debe tener título, autor e imagen no vacíos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="US19_AC1c – Búsqueda sin coincidencias")]
        [Xunit.TraitAttribute("FeatureTitle", "US19 – Buscar libros y contenido en la aplicación")]
        [Xunit.TraitAttribute("Description", "US19_AC1c – Búsqueda sin coincidencias")]
        public void US19_AC1CBusquedaSinCoincidencias()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("US19_AC1c – Búsqueda sin coincidencias", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
  this.FeatureBackground();
#line hidden
#line 32
    testRunner.Given("el lector inicia una consulta de búsqueda", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 33
    testRunner.When("el sistema recibe el término \"Harry Potter\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 34
    testRunner.Then("el sistema debe retornar una lista vacía de resultados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="US19_AC2a – Búsqueda por autor completo")]
        [Xunit.TraitAttribute("FeatureTitle", "US19 – Buscar libros y contenido en la aplicación")]
        [Xunit.TraitAttribute("Description", "US19_AC2a – Búsqueda por autor completo")]
        public void US19_AC2ABusquedaPorAutorCompleto()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("US19_AC2a – Búsqueda por autor completo", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
  this.FeatureBackground();
#line hidden
#line 37
    testRunner.Given("el lector desea encontrar obras de un autor en particular", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 38
    testRunner.When("el sistema recibe el nombre del autor \"Gabriel García Márquez\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 39
    testRunner.Then("el sistema debe retornar todos los libros de ese autor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 40
    testRunner.And("el número de resultados debe ser 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 41
    testRunner.And("cada resultado debe pertenecer al autor \"Gabriel García Márquez\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="US19_AC2b – Búsqueda por apellido parcial del autor")]
        [Xunit.TraitAttribute("FeatureTitle", "US19 – Buscar libros y contenido en la aplicación")]
        [Xunit.TraitAttribute("Description", "US19_AC2b – Búsqueda por apellido parcial del autor")]
        public void US19_AC2BBusquedaPorApellidoParcialDelAutor()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("US19_AC2b – Búsqueda por apellido parcial del autor", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 43
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
  this.FeatureBackground();
#line hidden
#line 44
    testRunner.Given("el lector desea encontrar obras de un autor en particular", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 45
    testRunner.When("el sistema recibe el nombre del autor \"García\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 46
    testRunner.Then("el sistema debe retornar todos los libros de ese autor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 47
    testRunner.And("el número de resultados debe ser 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                US19BuscarLibrosYContenidoEnLaAplicacionFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                US19BuscarLibrosYContenidoEnLaAplicacionFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
